Repository HanghaeE5/Back-end, pull requests merged in 2022-07, with the labels that each got.

#34 비밀번호 변경, 스웨거 헤더 필수 요소
  src/main/java/com/example/backend/msg/MsgEnum.java
  src/main/java/com/example/backend/user/common/UserDetailsImpl.java
  src/main/java/com/example/backend/user/controller/LoginController.java
  src/main/java/com/example/backend/user/controller/RegisterController.java
  src/main/java/com/example/backend/user/controller/UserController.java
  src/main/java/com/example/backend/user/domain/User.java
  src/main/java/com/example/backend/user/dto/PasswordRequestDto.java
  src/main/java/com/example/backend/user/dto/RegisterRequestDto.java
  src/main/java/com/example/backend/user/service/UserService.java
Labels: documentation, enhancement

#61 Feature/communities
  src/main/java/com/example/backend/board/dto/response/BoardResponseDto.java
  src/main/java/com/example/backend/board/service/BoardService.java
  src/main/java/com/example/backend/chat/config/handler/StompHandler.java
  src/main/java/com/example/backend/chat/controller/ChatMessageController.java
  src/main/java/com/example/backend/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/com/example/backend/chat/service/ChatMessageService.java
  src/main/java/com/example/backend/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/backend/user/config/SecurityConfig.java
  src/main/java/com/example/backend/user/token/AuthTokenProvider.java
Labels: bug, enhancement

#73 #28 회원가입시 기본 이미지
  src/main/java/com/example/backend/user/domain/User.java
  src/main/java/com/example/backend/user/service/CustomOAuth2UserService.java
  src/main/java/com/example/backend/user/service/UserService.java
Labels: enhancement

#81 Feature/event, 이벤트 기능 초기모델 완료
  src/main/java/com/example/backend/BackEndApplication.java
  src/main/java/com/example/backend/board/domain/Board.java
  src/main/java/com/example/backend/character/domain/Characters.java
  src/main/java/com/example/backend/event/controller/EventController.java
  src/main/java/com/example/backend/event/domain/Event.java
  src/main/java/com/example/backend/event/domain/Product.java
  src/main/java/com/example/backend/event/domain/Stamp.java
  src/main/java/com/example/backend/event/domain/StampDate.java
  src/main/java/com/example/backend/event/domain/Winning.java
  src/main/java/com/example/backend/event/dto/EventRequestDto.java
  src/main/java/com/example/backend/event/dto/EventResponseDto.java
  src/main/java/com/example/backend/event/dto/ProductResponseDto.java
  src/main/java/com/example/backend/event/repository/EventRepository.java
  src/main/java/com/example/backend/event/repository/ProductRepository.java
  src/main/java/com/example/backend/event/repository/StampDateRepository.java
  src/main/java/com/example/backend/event/repository/StampRepository.java
  src/main/java/com/example/backend/event/repository/WinningRepository.java
  src/main/java/com/example/backend/event/scheduler/EventScheduler.java
  src/main/java/com/example/backend/event/service/EventService.java
  src/main/java/com/example/backend/exception/ErrorCode.java
  src/main/java/com/example/backend/msg/MsgEnum.java
  src/main/java/com/example/backend/todo/domain/Todo.java
  src/main/java/com/example/backend/todo/repository/TodoRepository.java
  src/main/java/com/example/backend/user/config/SecurityConfig.java
  src/main/java/com/example/backend/user/domain/User.java
  src/main/java/com/example/backend/user/repository/UserRepository.java
  src/main/java/com/example/backend/user/service/CustomOAuth2UserService.java
  src/main/java/com/example/backend/user/service/UserService.java
  src/test/java/com/example/backend/event/PercentTest.java
Labels: enhancement

#84 펄미션
  src/main/java/com/example/backend/user/config/SecurityConfig.java
Labels: bug

#97 #75 스케줄러시간 12:05분으로 조정
  src/main/java/com/example/backend/event/scheduler/EventScheduler.java
Labels: enhancement

#108 #10 참여중 flag 수정
  src/main/java/com/example/backend/board/controller/BoardController.java
  src/main/java/com/example/backend/board/dto/response/BoardResponseDto.java
  src/main/java/com/example/backend/board/service/BoardService.java
Labels: enhancement

#113 #6 Refresh Token, Access Token
  src/main/java/com/example/backend/event/dto/ProductResponseDto.java
  src/main/java/com/example/backend/swagger/SwaggerConfig.java
  src/main/java/com/example/backend/user/config/SecurityConfig.java
  src/main/java/com/example/backend/user/controller/LoginController.java
  src/main/java/com/example/backend/user/controller/RegisterController.java
  src/main/java/com/example/backend/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/backend/user/service/CustomOAuth2UserService.java
  src/main/java/com/example/backend/user/service/CustomUserDetailsService.java
  src/main/java/com/example/backend/user/service/UserService.java
Labels: bug, enhancement

#114 #23 스웨거 refresh 부분 제거
  src/main/java/com/example/backend/swagger/SwaggerConfig.java
Labels: bug, enhancement

#116 Feature/login Refresh Token 관리 포인트 DB로
  src/main/java/com/example/backend/user/controller/LoginController.java
  src/main/java/com/example/backend/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/backend/user/service/UserService.java
  src/main/java/com/example/backend/user/utils/CookieUtil.java
Labels: bug, enhancement

#131 #10 커뮤니티 목록 조회 정렬
  src/main/java/com/example/backend/board/repository/BoardRepositoryImpl.java
Labels: enhancement

#142 #141 slack 오류 대응
  build.gradle
  src/main/java/com/example/backend/user/utils/CookieUtil.java
  src/main/resources/logback-spring.xml
Labels: documentation

#173 이벤트 응모권 받는 부분 3일로 변경
  src/main/java/com/example/backend/board/repository/BoardRepositoryImpl.java
  src/main/java/com/example/backend/event/domain/Stamp.java
  src/main/java/com/example/backend/event/scheduler/EventScheduler.java
  src/main/java/com/example/backend/event/service/EventService.java
  src/main/java/com/example/backend/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/backend/user/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/example/backend/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/backend/user/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/example/backend/user/service/UserService.java
  src/main/java/com/example/backend/utils/CookieUtil.java
  src/main/java/com/example/backend/utils/HeaderUtil.java
Labels: enhancement

#174 #10 이미지 수정 시
  src/main/java/com/example/backend/board/service/BoardService.java
Labels: bug

#176 #141 많은 오류 메시지 때문에 주석 처리
  src/main/resources/logback-spring.xml
Labels: bug

#181 #75 이벤트 스케줄러 동시성 Redis 이용
  build.gradle
  scripts/run_new_was.sh
  src/main/java/com/example/backend/BackEndApplication.java
  src/main/java/com/example/backend/config/SchedulerConfig.java
  src/main/java/com/example/backend/event/scheduler/EventScheduler.java
  src/main/java/com/example/backend/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/backend/user/service/UserService.java
Labels: bug

#185 #5
  src/main/java/com/example/backend/todo/repository/TodoRepository.java
  src/main/java/com/example/backend/todo/service/TodoService.java
Labels: enhancement

#190 메인에 먼저 머지했던거
  README.md
  build.gradle
  src/main/java/com/example/backend/config/AsyncConfig.java
  src/main/java/com/example/backend/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/backend/mail/EmailService.java
  src/main/java/com/example/backend/mail/HtmlEmailService.java
  src/main/java/com/example/backend/msg/MsgEnum.java
  src/main/java/com/example/backend/user/controller/RegisterController.java
  src/main/java/com/example/backend/user/domain/EmailCheck.java
  src/main/java/com/example/backend/user/service/UserService.java
  src/main/resources/templates/mail.html
Labels: enhancement
